[connection]
# The URI of the server you will be connecting to.
uri = "some.org:7687"

# Your database user ID.
user = ""

# Your database password.
pass = ""

[task]
# Read this CSV for processing.
csv_path = "neo4j_setup/imports/some.csv"
