version: '3.5'
services:
  neo4j:
    restart: always
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - test
    volumes:
      - ./scripts/neo4j_volumes/data:/var/lib/neo4j/data
      - ./scripts/neo4j_volumes/logs:/var/lib/neo4j/logs
      - ./scripts/neo4j_volumes/conf:/var/lib/neo4j/conf
      - ./scripts/neo4j_volumes/import:/var/lib/neo4j/import
      - ./scripts/neo4j_volumes/plugins:/var/lib/neo4j/plugins
networks:
  test: