apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: polar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: neo4j
  template:
    metadata:
      labels:
        name: neo4j
      name: neo4j
    spec:
      containers:
        - image: docker.io/library/neo4j:4.4.42
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - mountPath: /var/lib/neo4j/conf
              name: neo4j-data
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-pvc
