apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: polar
spec:
  ports:
    - name: http-ui
      nodePort: 30074
      port: 7474
      targetPort: 7474
    - name: bolt
      nodePort: 30087
      port: 7687
      targetPort: 7687
  selector:
    name: neo4j
  type: NodePort
