apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data
  namespace: polar
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "10Gi"
  hostPath:
    path: /data/conf
  storageClassName: standard
