version: '3'

services:
  neo4j:
    image: neo4j:5.8.0-community
    restart: unless-stopped
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j-data:/data

  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - '5672:5672'

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
volumes:
  neo4j-data: