use std::collections::HashMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Cassini subjects the orchestrator agents are interested in
/// Mirrors the subject constants defined in cyclops-core.
pub mod subjects {
    pub const BUILD_EVENTS_TOPIC: &str = "polar.orchestrator.builds..events";
    pub const BUILD_REQUESTS_TOPIC: &str = "polar.orchestrator.builds.requests";
}

/// The inbound payload published by Polar's scheduler onto the Cassini broker.
/// This is the authoritative wire format — do not add fields without versioning.
/// Image resolution is the orchestrator's responsibility, not the scheduler's.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildRequest {
    /// Stable identifier for this build. Generated by the scheduler.
    pub build_id: Uuid,

    /// Full HTTPS or SSH URL to the source repository.
    pub repo_url: String,

    /// Full 40-character commit SHA. Never a branch name or tag — those are mutable.
    pub commit_sha: String,

    /// Opaque identity string from Polar representing who or what requested the build.
    pub requested_by: String,

    /// Wall-clock time the scheduler emitted this request.
    pub requested_at: DateTime<Utc>,
    pub target_registry: String,

    /// Arbitrary key-value metadata forwarded from the scheduler.
    /// Used for forward-compatibility — do not rely on specific keys in core logic.
    #[serde(default)]
    pub metadata: HashMap<String, String>,
}

/// The state machine for a single build lifecycle.
///
/// The two-phase image resolution flow sits before actual execution:
///
///   Pending
///     └─► ResolvingImage          ← check registry for pipeline image
///           ├─► Bootstrapping     ← image missing: run bootstrap job to build it
///           │     └─► Scheduled   ← bootstrap done, now schedule the real job
///           └─► Scheduled         ← image present, proceed directly
///                 └─► Running
///                       ├─► Succeeded
///                       └─► Failed
///
/// Cancelled is reachable from any non-terminal state.
/// Failed is reachable from ResolvingImage, Bootstrapping, Scheduled, and Running.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuildState {
    /// Received and validated. Image resolution has not started yet.
    Pending,

    /// Checking the registry for the pipeline image for this repo.
    ResolvingImage,

    /// Pipeline image was not found. A bootstrap job is running to build it.
    /// The bootstrap job uses the well-known base Nix builder image from config.
    Bootstrapping,

    /// Pipeline image is confirmed present. Build job submitted to the backend.
    Scheduled,

    /// Backend has confirmed the job is actively running.
    Running,

    /// Job completed successfully. Artifact produced.
    Succeeded,

    /// Job terminated with a failure at any stage.
    Failed,

    /// Cancelled before reaching a terminal state.
    Cancelled,
}

impl BuildState {
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Succeeded | Self::Failed | Self::Cancelled)
    }

    pub fn can_transition_to(&self, next: &BuildState) -> bool {
        use BuildState::*;
        matches!(
            (self, next),
            // Normal forward path
            (Pending, ResolvingImage)
            | (ResolvingImage, Bootstrapping)
            | (ResolvingImage, Scheduled)   // image was already present
            | (Bootstrapping, Scheduled)    // bootstrap completed, image now exists
            | (Scheduled, Running)
            | (Running, Succeeded)
            // Failure from any active state
            | (ResolvingImage, Failed)
            | (Bootstrapping, Failed)
            | (Scheduled, Failed)
            | (Running, Failed)
            // Cancellation from any non-terminal state
            | (Pending, Cancelled)
            | (ResolvingImage, Cancelled)
            | (Bootstrapping, Cancelled)
            | (Scheduled, Cancelled)
            | (Running, Cancelled)
        )
    }
}

impl std::fmt::Display for BuildState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            BuildState::Pending => "pending",
            BuildState::ResolvingImage => "resolving_image",
            BuildState::Bootstrapping => "bootstrapping",
            BuildState::Scheduled => "scheduled",
            BuildState::Running => "running",
            BuildState::Succeeded => "succeeded",
            BuildState::Failed => "failed",
            BuildState::Cancelled => "cancelled",
        };
        write!(f, "{}", s)
    }
}

/// Operational record maintained in the registry actor for the duration of a build.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildRecord {
    pub build_id: Uuid,
    pub state: BuildState,
    pub request: BuildRequest,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    /// Opaque handle returned by the backend on submission.
    /// None until Scheduled.
    pub backend_handle: Option<String>,
    /// Digest of the resolved pipeline image.
    /// Populated once ResolvingImage or Bootstrapping completes successfully.
    pub resolved_image: Option<String>,
    /// Human-readable reason for failure or cancellation, if applicable.
    pub failure_reason: Option<String>,
}

impl BuildRecord {
    pub fn new(request: BuildRequest) -> Self {
        let now = Utc::now();
        Self {
            build_id: request.build_id,
            state: BuildState::Pending,
            request,
            created_at: now,
            updated_at: now,
            backend_handle: None,
            resolved_image: None,
            failure_reason: None,
        }
    }

    pub fn transition(&mut self, next: BuildState) -> Result<(), crate::error::CyclopsError> {
        if self.state.can_transition_to(&next) {
            tracing::debug!(
                build_id = %self.build_id,
                from = %self.state,
                to = %next,
                "build state transition"
            );
            self.state = next;
            self.updated_at = Utc::now();
            Ok(())
        } else {
            Err(crate::error::CyclopsError::InvalidStateTransition {
                from: self.state.clone(),
                to: next,
            })
        }
    }
}

/// Fully resolved specification handed to the backend for a pipeline job.
///
/// By the time this is constructed, image resolution is complete — the pipeline
/// image digest is known and confirmed present in the registry. The backend
/// uses this to build the Kubernetes Job manifest.
///
/// Source code is NOT baked into the image. An init container clones the repo
/// into a shared emptyDir volume at /workspace before the pipeline container
/// starts. See job.rs for the init container implementation.
#[derive(Debug, Clone)]
pub struct BuildSpec {
    pub build_id: Uuid,
    pub repo_url: String,
    pub commit_sha: String,

    /// Fully qualified pipeline image reference, pinned by digest.
    /// e.g. "registry.internal.example.com/builds/myapp@sha256:abc123..."
    /// The image must have /bin/pipeline-runner as its entrypoint.
    pub pipeline_image: String,

    /// Entrypoint override. None means the image's own CMD is used, which
    /// must be /bin/pipeline-runner. Only set this in tests.
    pub entrypoint: Option<Vec<String>>,

    pub target_registry: String,

    /// Credentials for cloning the source repository.
    /// The referenced Secret must exist in the build namespace.
    pub git_credentials: GitCredentials,

    /// Credentials for pulling the pipeline image from the registry.
    /// The referenced Secret must be of type kubernetes.io/dockerconfigjson.
    pub registry_credentials: RegistryCredentials,

    /// Additional env vars injected into the pipeline container.
    /// Standard Cyclops vars (build ID, repo, commit, registry) are always
    /// injected by the manifest builder and should not be duplicated here.
    pub env: HashMap<String, String>,
}

impl BuildSpec {
    pub fn with_pipeline_runner(
        build_id: Uuid,
        repo_url: String,
        commit_sha: String,
        pipeline_image: String,
        target_registry: String,
        git_credentials: GitCredentials,
        registry_credentials: RegistryCredentials,
    ) -> Self {
        Self {
            build_id,
            repo_url,
            commit_sha,
            pipeline_image,
            entrypoint: None,
            target_registry,
            git_credentials,
            registry_credentials,
            env: HashMap::new(),
        }
    }
}

/// Specification for a bootstrap job.
///
/// A bootstrap job is run when no pipeline image exists yet for a given repo.
/// It uses the a well known, configured build environment and runs a known command
/// and produce the repo-specific pipeline image, pushing it to the registry.
///
/// Bootstrap jobs use the same init container clone pattern as pipeline jobs —
/// the Nix evaluator needs the source.
///
/// Once the bootstrap job completes and pushes the image, the orchestrator
/// records the resulting digest against the repo URL so subsequent builds
/// skip bootstrapping entirely.
#[derive(Debug, Clone)]
pub struct BootstrapSpec {
    pub build_id: Uuid,
    pub repo_url: String,
    pub commit_sha: String,

    /// The well-known base Nix builder image. Pinned by digest in config.
    /// This image knows how to evaluate Dhall and run nix build. It is built
    /// manually and changes only when the Nix evaluation environment changes.
    pub bootstrap_image: String,

    /// Path within the repo to the Dhall config defining the pipeline container.
    /// Convention-based — defaults to "container.dhall" at repo root.
    pub container_config_ref: String,

    /// Where to push the resulting pipeline image once built.
    pub target_registry: String,

    /// Credentials for cloning the source repository.
    pub git_credentials: GitCredentials,

    /// Credentials for pushing the produced image to the registry.
    /// Must have push access to target_registry.
    pub registry_credentials: RegistryCredentials,
}

// ── Credential types ──────────────────────────────────────────────────────────

/// Describes how the init container should authenticate to the git host
/// when cloning the source repository.
///
/// These map to Kubernetes Secrets that must already exist in the build
/// namespace before any job runs. Provisioning those secrets is an
/// infrastructure concern, not an orchestrator concern — the orchestrator
/// only needs to know which secret to reference in the Job manifest.
///
/// SSH key support is intentionally absent here. It will be added once the
/// identity root agent can issue short-lived SSH credentials per job, which
/// removes the need to manage long-lived key secrets entirely.
#[derive(Debug, Clone)]
pub enum GitCredentials {
    /// HTTP basic auth or token auth (GitLab deploy token, GitHub PAT, etc.).
    /// The secret must contain a `username` key and a `password` key.
    /// For GitLab CI tokens the username is typically "gitlab-ci-token".
    HttpToken {
        /// Name of the Kubernetes Secret in the build namespace.
        secret_name: String,
    },
}

/// How the init container should authenticate to the container registry
/// when pulling the pipeline image or pushing bootstrap build output.
///
/// Azure ACR and other registries that support OCI token exchange are handled
/// here. The orchestrator injects these as imagePullSecrets on the pod spec
/// and as env vars for the bootstrap push step.
///
/// Long-term, ACR managed identity via workload identity federation replaces
/// this entirely — the pod gets an AAD token from the identity root agent and
/// exchanges it for an ACR refresh token at pull time. Until then, static
/// secrets it is.
#[derive(Debug, Clone)]
pub enum RegistryCredentials {
    /// A standard dockerconfigjson secret. Works for ACR, GCR, ECR, and
    /// any registry that speaks Docker Hub auth protocol.
    /// Must be of type kubernetes.io/dockerconfigjson.
    DockerConfigJson {
        /// Name of the Kubernetes Secret in the build namespace.
        secret_name: String,
    },
}
