apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-agent
  namespace: polar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitlab-agent
  template:
    metadata:
      labels:
        name: gitlab-agent
      name: gitlab-agent
    spec:
      containers:
        - env:
            - name: TLS_CA_CERT
              value: /etc/cassini/tls/ca_certificate.pem
            - name: TLS_CLIENT_CERT
              value: /etc/tls/client_polar_certificate.pem
            - name: TLS_CLIENT_KEY
              value: /etc/tls/client_polar_key.pem
            - name: BROKER_ADDR
              value: cassini-ip-svc.polar.svc.cluster.local:8080
            - name: GITLAB_ENDPOINT
              value: https://gitlab.sandbox.labz.s-box.org/api/graphql
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: gitlab-secret
          image: localhost/polar-gitlab-observer:0.1.0
          name: gitlab-observer
          volumeMounts:
            - mountPath: /etc/tls
              name: client-mtls
        - env:
            - name: TLS_CA_CERT
              value: /etc/cassini/tls/ca_certificate.pem
            - name: TLS_CLIENT_CERT
              value: /etc/tls/client_polar_certificate.pem
            - name: TLS_CLIENT_KEY
              value: /etc/tls/client_polar_key.pem
            - name: BROKER_ADDR
              value: cassini-ip-svc.polar.svc.cluster.local:8080
            - name: GRAPH_ENDPOINT
              value: neo4j-svc.polar.svc.cluster.local:7474
            - name: GRAPH_DB
              value: neo4j
            - name: GRAPH_USERNAME
              value: neo4j
            - name: GRAPH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: token
                  name: neo4j-secret
          image: localhost/polar-gitlab-consumer:0.1.0
          name: gitlab-consumer
          volumeMounts:
            - mountPath: /etc/tls
              name: client-mtls
              readOnly: true
      volumes:
        - name: client-mtls
          secret:
            secretName: client-mtls
