kubectl apply -f ./namespace.yaml 
kubectl apply -f ./namespace2.yaml 
kubectl apply -f ./configmap.yaml 
kubectl apply -f ./data-pvc.yaml 
kubectl apply -f ./logs-pvc.yaml
kubectl apply -f ./cassini-client-certificate.yaml
kubectl apply -f ./cassini-svc.yaml
kubectl apply -f ./neo4j-secret.yaml
kubectl apply -f ./graph-secret.yaml
kubectl apply -f ./ca-issuer.yaml
kubectl apply -f ./role-binding.yaml
kubectl apply -f ./role-binding2.yaml
kubectl apply -f ./mtls-ca.yaml
kubectl apply -f ./leaf-issuer.yaml
kubectl apply -f ./cassini-server-cert.yaml
kubectl apply -f ./cassini-deployment.yaml
kubectl apply -f neo4j-statefulset.yaml
kubectl apply -f neo4j-service.yaml
kubectl apply -f neo4j-virtualservice.yaml
kubectl apply -f proxy-ca-cert.yaml
kubectl apply -f gitlab-crt.yaml
kubectl apply -f gitlab-secret.yaml
kubectl apply -f gitlab-agent-serviceaccount.yaml
kubectl apply -f gitlab-agent-deployment.yaml
kubectl apply -f kube-agent-sa.yaml
kubectl apply -f kube-token.yaml
kubectl apply -f kube-agent-deployment.yaml
