apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassini
  namespace: polar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cassini
  template:
    metadata:
      labels:
        name: cassini
      name: cassini
    spec:
      containers:
        - env:
            - name: TLS_CA_CERT
              value: /etc/cassini/tls/ca_certificate.pem
            - name: TLS_SERVER_CERT_CHAIN
              value: /etc/cassini/tls/server_polar_certificate.pem
            - name: TLS_SERVER_KEY
              value: /etc/cassini/tls/server_polar_key.pem
            - name: CASSINI_BIND_ADDR
              value: "0.0.0.0:8080"
          image: localhost/cassini:0.1.0
          name: cassini
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/cassini/tls
              name: mtls-secrets
              readOnly: true
      volumes:
        - name: mtls-secrets
          secret:
            secretName: cassini-mtls
