use neo4rs::BoltType;
use polar::graph::controller::GraphNodeKey;
use serde::{Deserialize, Serialize};
use std::fmt::Debug;
pub mod build;
pub mod linker;
pub mod projection;
pub mod supervisor;
pub const BROKER_CLIENT_NAME: &str = "provenance.linker.tcp";
pub const AGENT_NAME: &str = "polar.bullds.orchestrator";
