[package]
name = "cassini"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
ractor = { version="0.14.1"}
serde = {version = "1.0.216", features = ["derive"]}
serde_json = "1.0.133"
tokio = { version = "1.30", features = ["full"] }
tracing = "0.1.41"
tracing-glog = "0.4.0"
tracing-subscriber = { version ="0.3.19", features=["std", "env-filter"]}
uuid = { version = "1.11.0", features = ["v4"] }
tokio-util = "0.7.13"
rustls = "0.23.20"
tokio-rustls = "0.26.1"

[[bin]]
name = "cassini-server"
path = "src/main.rs"