# Polar (OSS)

# Copyright 2024 Carnegie Mellon University.

# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
# TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
# OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
# MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
# WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.

# Licensed under a MIT-style license, please see license.txt or contact
# permission@sei.cmu.edu for full terms.

# [DISTRIBUTION STATEMENT A] This material has been approved for public release
# and unlimited distribution.  Please see Copyright notice for non-US
# Government use and distribution.

# This Software includes and/or makes use of Third-Party Software each subject
# to its own license.

# DM24-0470

services:
  neo4j:
    user: 7474:7474
    image: registry1.dso.mil/ironbank/opensource/neo4j/neo4j:5.26.2
    restart: never
    environment:
      - NEO4J_AUTH=neo4j/somepassword
    networks:
      - polar
    ports:
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ../neo4j_setup/conf:/var/lib/neo4j/conf
      - ../certs/neo4j/ca_certificate.pem:/var/lib/neo4j/certificates/bolt/trusted/ca.crt
      - ../certs/neo4j/cert_chain.pem:/var/lib/neo4j/certificates/https/tls.crt
      - ../certs/neo4j/server_neo4j_key.pem:/var/lib/neo4j/certificates/https/tls.key
      - ../certs/neo4j/cert_chain.pem:/var/lib/neo4j/certificates/bolt/tls.crt
      - ../certs/neo4j/server_neo4j_key.pem:/var/lib/neo4j/certificates/bolt/tls.key
  cassini:
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/cassini:0.1.0
    networks:
      - polar
    ports:
        - 8080:8080
    environment:
      - CASSINI_BIND_ADDR=0.0.0.0:8080
      - TLS_CA_CERT=/etc/ssl/ca_certificate.pem
      - TLS_SERVER_CERT_CHAIN=/etc/ssl/server_cassini_certificate.pem
      - TLS_SERVER_KEY=/etc/ssl/server_cassini_key.pem
    volumes:
      - ../certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ../certs/server/server_cassini_key.pem:/etc/ssl/server_cassini_key.pem:ro
      - ../certs/server/server_cassini_certificate.pem:/etc/ssl/server_cassini_certificate.pem:ro    

  gitlab-observer:
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-gitlab-observer:0.1.0
    depends_on:
      - cassini
    env_file:
      - observer.env
    networks:
      - polar
    volumes:
      - ../certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ../certs/client/client_cassini_certificate.pem:/etc/ssl/client_cassini_certificate.pem:ro
      - ../certs/client/client_cassini_key.pem:/etc/ssl/client_cassini_key.pem:ro
      - ../certs/host/zscaler.pem:/etc/ssl/proxy_ca.pem:ro
      
  gitlab-consumer:
    image: registry.sandbox.labz.s-box.org/sei/polar-mirror/polar-gitlab-consumer:0.1.0
    depends_on:
      - cassini
      - neo4j
    env_file:
      - consumer.env
    networks:
      - polar
    volumes:
      - ../certs/ca_certificates/ca_certificate.pem:/etc/ssl/ca_certificate.pem:ro
      - ../certs/client/client_cassini_certificate.pem:/etc/ssl/client_cassini_certificate.pem:ro
      - ../certs/client/client_cassini_key.pem:/etc/ssl/client_cassini_key.pem:ro
      - ../certs/neo4j/ca_certificate.pem:/etc/graph/ca.crt:ro

networks:
  polar:

volumes:
  neo4j-data:
