[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapin = "2.2.1"
futures-lite = "1.13.0"
url = "2.3.1"
amq-protocol-uri = "7.1.2"
native-tls = "0.2.11"
tcp-stream = "0.26.1"
openssl = "0.10.56"
signal-hook = "0.3.17"
sysinfo = "0.29.10"
