[package]
name = "gitlab_types"
version = "0.1.0"
edition = "2021"

[lib]
name = "gitlab_types"
path = "src/types.rs"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
