backend:
  driver: kubernetes
  kubernetes:
    namespace: stub
    job_labels: []
cassini:
  broker_url: "nats://stub:4222"
  inbound_subject: "stub"
bootstrap:
  builder_image: "stub"
credentials:
  git_secret_name: stub
  registry_secret_name: stub
storage:
  endpoint_url: "http://stub:9000"
  access_key: stub
  secret_key: stub
  region: us-east-1
  bucket: stub
log:
  format: json
  level: info
