
server.jvm.additional=-Dunsupported.dbms.udc.source=docker

server.memory.heap.initial_size=2g
server.memory.heap.max_size=6g
# server.memory.pagecache.size=512M

server.http.enabled=false
server.https.enabled=true
server.https.listen_address=0.0.0.0:7473

server.logs.debug.enabled=true

server.bolt.tls_level=OPTIONAL
dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=/var/lib/neo4j/certificates/bolt
dbms.ssl.policy.bolt.client_auth=REQUIRE
server.bolt.enabled=true
server.bolt.listen_address=0.0.0.0:7687

# disable telemetry
dbms.usage_report.enabled=false

dbms.ssl.policy.https.enabled=true
dbms.ssl.policy.https.base_directory=/var/lib/neo4j/certificates/https
dbms.ssl.policy.https.client_auth=REQUIRE
#dbms.ssl.policy.https.client_auth=OPTIONAL

server.memory.pagecache.size=512M

server.default_listen_address=0.0.0.0
server.directories.import=/var/lib/neo4j/import
server.directories.logs=/var/lib/neo4j/logs
