dbms.ssl.policy.bolt.base_directory=/var/lib/neo4j/certificates/bolt
dbms.ssl.policy.bolt.client_auth=OPTIONAL
dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.https.base_directory=/var/lib/neo4j/certificates/https
dbms.ssl.policy.https.client_auth=OPTIONAL
dbms.ssl.policy.https.enabled=true
dbms.ssl.policy.https.trust_all=true

dbms.usage_report.enabled=false

server.bolt.enabled=true
server.bolt.listen_address=0.0.0.0:7687
server.bolt.tls_level=OPTIONAL

server.default_listen_address=0.0.0.0

server.directories.data=/var/lib/neo4j/data
server.directories.import=/var/lib/neo4j/import
server.directories.logs=/var/lib/neo4j/logs
server.directories.plugins=/var/lib/neo4j/plugins
server.directories.run=/var/lib/neo4j/run

server.http.enabled=false

server.https.enabled=true
server.https.listen_address=0.0.0.0:7473

server.jvm.additional=-Djavax.net.debug=ssl:handshake
server.jvm.additional=-Dunsupported.dbms.udc.source=docker
server.jvm.additional=-Djavax.net.ssl.trustStore=/var/lib/neo4j/conf/truststore.jks
server.jvm.additional=-Djavax.net.ssl.trustStorePassword=changeit

server.logs.debug.enabled=true

server.memory.heap.initial_size=2g
server.memory.heap.max_size=6g
server.memory.pagecache.size=512M
